"""
Static item catalog — seeded once on startup.
All boss names, item names, and lore are ORIGINAL (not Elden Ring IP).
"""

ITEMS = [
    {
        "item_key": "worn_shield",
        "name": "Worn Shield",
        "type": "armor",
        "rarity": "common",
        "description": "A sturdy wooden & iron shield. Absorbs crushing blows and is consumed in battle.",
        "price_echoes": 50,
        "is_purchasable": True,
        "unlock_boss_key": None,
        "vigor_bonus": 0,
        "strength_bonus": 0,
        "poise_bonus": 5,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "armor",
        "source": "shop",
        "pixel_art_key": "shield_worn",
    },
    {
        "item_key": "iron_sword",
        "name": "Iron Sword",
        "type": "weapon",
        "rarity": "common",
        "description": "A simple iron blade. Reliable in a pinch.",
        "price_echoes": 80,
        "is_purchasable": True,
        "unlock_boss_key": None,
        "vigor_bonus": 0,
        "strength_bonus": 8,
        "poise_bonus": 0,
        "is_consumable": False,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "weapon",
        "source": "shop",
        "pixel_art_key": "sword_iron",
    },
    {
        "item_key": "knights_helm",
        "name": "Knight's Helm",
        "type": "helmet",
        "rarity": "uncommon",
        "description": "A sturdy helm adorned with faded sigils. Absorbs lethal impacts and is consumed in battle.",
        "price_echoes": 120,
        "is_purchasable": True,
        "unlock_boss_key": None,
        "vigor_bonus": 15,
        "strength_bonus": 0,
        "poise_bonus": 4,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "helmet",
        "source": "shop",
        "pixel_art_key": "helm_knight",
    },
    {
        "item_key": "chain_mail",
        "name": "Chain Mail",
        "type": "armor",
        "rarity": "uncommon",
        "description": "Interlocked rings forged in the old kingdom. Defends the wearer and is consumed in battle.",
        "price_echoes": 150,
        "is_purchasable": True,
        "unlock_boss_key": None,
        "vigor_bonus": 20,
        "strength_bonus": 0,
        "poise_bonus": 8,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "armor",
        "source": "shop",
        "pixel_art_key": "armor_chain",
    },
    {
        "item_key": "soldiers_ring",
        "name": "Soldier's Ring",
        "type": "accessory",
        "rarity": "uncommon",
        "description": "A bronze ring worn by fallen order soldiers. Grants courage and is consumed in combat.",
        "price_echoes": 100,
        "is_purchasable": True,
        "unlock_boss_key": None,
        "vigor_bonus": 0,
        "strength_bonus": 5,
        "poise_bonus": 3,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "accessory",
        "source": "shop",
        "pixel_art_key": "ring_soldier",
    },
    {
        "item_key": "blessed_seal",
        "name": "Blessed Seal",
        "type": "accessory",
        "rarity": "rare",
        "description": "A golden seal that channels restorative energies. Imbues divine vigor and is consumed in battle.",
        "price_echoes": 200,
        "is_purchasable": True,
        "unlock_boss_key": "gravekeeper",
        "vigor_bonus": 30,
        "strength_bonus": 0,
        "poise_bonus": 0,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "accessory",
        "source": "shop",
        "pixel_art_key": "seal_blessed",
    },
    {
        "item_key": "rune_talisman",
        "name": "Rune Talisman",
        "type": "accessory",
        "rarity": "rare",
        "description": "Etched with ancient runes. Empowers both body and will and is consumed upon combat.",
        "price_echoes": 250,
        "is_purchasable": True,
        "unlock_boss_key": "shadow_warden",
        "vigor_bonus": 0,
        "strength_bonus": 12,
        "poise_bonus": 6,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "accessory",
        "source": "shop",
        "pixel_art_key": "talisman_rune",
    },
    {
        "item_key": "berserker_blade",
        "name": "Berserker's Blade",
        "type": "weapon",
        "rarity": "rare",
        "description": "A cleaver-like weapon that thirsts for combat.",
        "price_echoes": 320,
        "is_purchasable": True,
        "unlock_boss_key": "shadow_warden",
        "vigor_bonus": 0,
        "strength_bonus": 20,
        "poise_bonus": 0,
        "is_consumable": False,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "weapon",
        "source": "shop",
        "pixel_art_key": "sword_berserker",
    },
    {
        "item_key": "plate_armor",
        "name": "Plate Armor",
        "type": "armor",
        "rarity": "rare",
        "description": "Heavy plate forged beneath the ruins of a fallen citadel. Defends the wearer and is consumed upon combat.",
        "price_echoes": 350,
        "is_purchasable": True,
        "unlock_boss_key": "queen_of_ash",
        "vigor_bonus": 35,
        "strength_bonus": 0,
        "poise_bonus": 14,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "armor",
        "source": "shop",
        "pixel_art_key": "armor_plate",
    },
    {
        "item_key": "dragon_helm",
        "name": "Dragon Helm",
        "type": "helmet",
        "rarity": "rare",
        "description": "Crafted from scales of a long-dead dragon. Absorbs lethal impacts and is consumed in battle.",
        "price_echoes": 280,
        "is_purchasable": True,
        "unlock_boss_key": "queen_of_ash",
        "vigor_bonus": 25,
        "strength_bonus": 6,
        "poise_bonus": 6,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "helmet",
        "source": "shop",
        "pixel_art_key": "helm_dragon",
    },
    {
        "item_key": "dragonseal_armor",
        "name": "Dragonseal Armor",
        "type": "armor",
        "rarity": "legendary",
        "description": "Living scales of an ancient dragon sealed into armor.",
        "price_echoes": 400,
        "is_purchasable": True,
        "unlock_boss_key": "void_sovereign",
        "vigor_bonus": 50,
        "strength_bonus": 0,
        "poise_bonus": 22,
        "is_consumable": False,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "armor",
        "source": "shop",
        "pixel_art_key": "armor_dragonseal",
    },
    {
        "item_key": "godslayer_sword",
        "name": "Godslayer's Sword",
        "type": "weapon",
        "rarity": "legendary",
        "description": "A blade that once felled a divine being. Its edge still hungers.",
        "price_echoes": 600,
        "is_purchasable": True,
        "unlock_boss_key": "void_sovereign",
        "vigor_bonus": 0,
        "strength_bonus": 35,
        "poise_bonus": 0,
        "is_consumable": False,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "weapon",
        "source": "shop",
        "pixel_art_key": "sword_godslayer",
    },
    {
        "item_key": "ancient_bulwark",
        "name": "Ancient Bulwark",
        "type": "armor",
        "rarity": "legendary",
        "description": "The shield of a forgotten god. Provides immense poise defense in battle and is consumed upon use.",
        "price_echoes": 500,
        "is_purchasable": True,
        "unlock_boss_key": "eternal_sovereign",
        "vigor_bonus": 40,
        "strength_bonus": 0,
        "poise_bonus": 30,
        "is_consumable": True,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "armor",
        "source": "shop",
        "pixel_art_key": "armor_ancient",
    },
    {
        "item_key": "elden_medallion",
        "name": "Elden Medallion",
        "type": "accessory",
        "rarity": "legendary",
        "description": "The final seal of the Elden order. It radiates boundless power.",
        "price_echoes": 500,
        "is_purchasable": True,
        "unlock_boss_key": "eternal_sovereign",
        "vigor_bonus": 30,
        "strength_bonus": 15,
        "poise_bonus": 15,
        "is_consumable": False,
        "consumable_effect": {},
        "is_stackable": False,
        "max_stack": 1,
        "slot": "accessory",
        "source": "shop",
        "pixel_art_key": "medallion_elden",
    },
]

# Starter items given to every new character
STARTER_ITEM_KEYS = ["worn_shield", "iron_sword"]
